# Generated by Django 5.0 on 2023-12-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_shemach_quantityoil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shemach',
            name='quantityOil',
            field=models.DecimalField(choices=[(0, 'None'), (3, '3 lts'), (5, '5 lts')], decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='shemach',
            name='quantitySugar',
            field=models.DecimalField(choices=[(0, 'None'), (3, '3 kg'), (5, '5 kg')], decimal_places=2, default=0, max_digits=5),
        ),
    ]
