# Generated by Django 5.0 on 2023-12-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_shemach_quantityoil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shemach',
            name='residentId',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
